plugins {
    id 'java-library'
    id 'net.neoforged.moddev' version '2.0.107'
}

version = mod_version
group = mod_group_id

base {
    archivesName = mod_id
}

java.toolchain.languageVersion = JavaLanguageVersion.of(21)

repositories {
    maven { url = 'https://api.modrinth.com/maven' }
}

neoForge {
    version = neoforge_version

    runs {
        client {
            client()
            gameDirectory = project.file('run/client')
        }
        server {
            server()
            gameDirectory = project.file('run/server')
            programArgument '--nogui'
        }
    }

    mods {
        "${mod_id}" {
            sourceSet sourceSets.main
        }
    }
}

dependencies {
    implementation "maven.modrinth:pipez:${pipez_maven_version}"
}

tasks.named('processResources', ProcessResources).configure {
    def replacements = [
            minecraft_version: minecraft_version,
            neoforge_version  : neoforge_version,
            pipez_version     : pipez_version,
            mod_id            : mod_id,
            mod_name          : mod_name,
            mod_version       : mod_version
    ]
    inputs.properties replacements
    filesMatching('META-INF/neoforge.mods.toml') {
        expand replacements
    }
}

tasks.withType(JavaCompile).configureEach {
    options.encoding = 'UTF-8'
}
