org.gradle.jvmargs=-Xmx3G
org.gradle.daemon=false
org.gradle.configuration-cache=false

minecraft_version=1.20.1
forge_version=47.4.22
forge_dependency_version=47.4.10
pipez_version=1.20.1-1.2.26
pipez_maven_version=forge-1.20.1-1.2.26

mod_id=advanced_pipez_utilities
mod_name=Advanced Pipez Utilities
mod_version=1.0.0
mod_group_id=jp.yuuki.advancedpipezutilities
