modLoader = "javafml"
loaderVersion = "[47,)"
license = "MIT"

[[mods]]
modId = "${mod_id}"
version = "${mod_version}"
displayName = "${mod_name}"
authors = "yuuki1293"
description = '''
GregTech-style manual connections and an advanced wrench for Pipez.
'''

[[dependencies.${mod_id}]]
modId = "forge"
mandatory = true
versionRange = "[${forge_dependency_version},)"
ordering = "NONE"
side = "BOTH"

[[dependencies.${mod_id}]]
modId = "minecraft"
mandatory = true
versionRange = "[${minecraft_version},1.20.2)"
ordering = "NONE"
side = "BOTH"

[[dependencies.${mod_id}]]
modId = "pipez"
mandatory = true
versionRange = "[${pipez_version},)"
ordering = "AFTER"
side = "BOTH"
