modLoader = "javafml"
loaderVersion = "[4,)"
license = "MIT"

[[mods]]
modId = "${mod_id}"
version = "${mod_version}"
displayName = "${mod_name}"
authors = "yuuki1293"
description = '''
GregTech-style manual connections and an advanced wrench for Pipez.
'''

[[dependencies.${mod_id}]]
modId = "neoforge"
type = "required"
versionRange = "[${neoforge_version},)"
ordering = "NONE"
side = "BOTH"

[[dependencies.${mod_id}]]
modId = "minecraft"
type = "required"
versionRange = "[${minecraft_version},1.21.2)"
ordering = "NONE"
side = "BOTH"

[[dependencies.${mod_id}]]
modId = "pipez"
type = "required"
versionRange = "[${pipez_version},)"
ordering = "AFTER"
side = "BOTH"

[[mixins]]
config = "advanced_pipez_utilities.mixins.json"
